M48
; DRILL file {KiCad 7.0.7} date Sun Feb 25 20:38:03 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-25T20:38:03+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1181
%
G90
G05
T1
X1.4354Y-3.937
X1.4354Y-4.037
T2
X1.4567Y-1.7717
X1.4567Y-3.6201
X2.4217Y-1.7717
X2.4217Y-3.6201
T0
M30
